name: Pranav Sanghavi

url: https://pranavsanghavi.com
source: .
destination: ./_site
collections_dir: .
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
include: ["_pages"]

collections:
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
