name: Pranav Sanghavi
email: prnv.snghv
url: https://pranavsanghavi.com
source: .
destination: ./_site
#collections_dir: .
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
include: ["_pages"]

collections:
  posts:
    output: true

plugins:
  - jekyll-toc
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

toc:
  min_level: 1
  max_level: 6
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ""
  item_class: toc-entry
  item_prefix: toc-
